version: "3.1"
services:
  database:
    image: mariadb:10.5
    ports:
      - "3308:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=iamgroot"
  application:
    environment:
      - "CLIENT_ID=${CLIENT_ID}"
      - "CLIENT_SECRET=${CLIENT_SECRET}"