chicken:
  rollen:
    tutor:
    orga:

spring:
  flyway:
    schemas: chicken
    create-schemas: true
    url: jdbc:mariadb://localhost:3308/
    user: root
    password: iamgroot
  datasource:
    url: jdbc:mariadb://localhost:3308/chicken
    username: root
    password: iamgroot

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
