= Lösungsstrategie

== Technologieentscheidungen

Die Anwendung ist eine Spring-Boot Webapplikation, die mit Gradle gebaut wird.
Der Code im Back-End ist vollständig in Java 17 geschrieben, das Front-End in HTML 5 mit Bootstrap5-CSS-Framework, wobei wir hier zur Anbindung der Views an das Back-End Thymeleaf verwendet haben.

Für eine effiziente Nutzung der Systemressourcen und die Gewährleistung der Lauffähigkeit unserer Anwendung auf möglichst vielen Systemen benutzen wir die Containerisierungstechnologie Docker (bzw. docker-compose).

Während des Entwicklungsprozesses wird die Codequalität kontinuierlich durch das Continous-Integration System Github-Actions sichergestellt.

== Architekturentscheidungen

Wir nutzen für die Umsetzung von Bounded Contexts nach Domain-Driven Design die Onion-architecture

== Organisationsentscheidungen

Zur Verwaltung unserer gemeinsamen Entwicklung nutzen wir alle von Github bereitgestellten Dienste.
Das sind im Wesentlichen:

- *Git-Versionsverwaltungssoftware*: Sowohl zur Erfassung von Änderungen an Code oder Dateien als auch für das Zurückgreifen bei Bedarf auf einen früheren Stand unseres Projektes.

Zusätzlich haben wir beschlossen, jeden Tag Abend nach dem Praktikum nochmal gemeinsam an die Anwendung weiterzuarbeiten.
Wir benutzen Discord, whatsapp, und microsoft Teams um die Kommunikation miteinander zu erleichtern.